# -*- coding: utf-8 -*-

us_state_to_code = {
    'Alabama': 'AL',
    'Alaska': 'AK',
    'American_Samoa': 'AS',
    'Arizona': 'AZ',
    'Arkansas': 'AR',
    'California': 'CA',
    'Colorado': 'CO',
    'Connecticut': 'CT',
    'Delaware': 'DE',
    'District_of_Columbia': 'DC',
    'Florida': 'FL',
    'Georgia': 'GA',
    'Guam': 'GU',
    'Hawaii': 'HI',
    'Idaho': 'ID',
    'Illinois': 'IL',
    'Indiana': 'IN',
    'Iowa': 'IA',
    'Kansas': 'KS',
    'Kentucky': 'KY',
    'Louisiana': 'LA',
    'Maine': 'ME',
    'Maryland': 'MD',
    'Massachusetts': 'MA',
    'Michigan': 'MI',
    'Minnesota': 'MN',
    'Mississippi': 'MS',
    'Missouri': 'MO',
    'Montana': 'MT',
    'Nebraska': 'NE',
    'Nevada': 'NV',
    'New_Hampshire': 'NH',
    'New_Jersey': 'NJ',
    'New_Mexico': 'NM',
    'New_York': 'NY',
    'North_Carolina': 'NC',
    'North_Dakota': 'ND',
    'Northern_Mariana_Islands':'MP',
    'Ohio': 'OH',
    'Oklahoma': 'OK',
    'Oregon': 'OR',
    'Pennsylvania': 'PA',
    'Puerto_Rico': 'PR',
    'Rhode_Island': 'RI',
    'South_Carolina': 'SC',
    'South_Dakota': 'SD',
    'Tennessee': 'TN',
    'Texas': 'TX',
    'Utah': 'UT',
    'Vermont': 'VT',
    'Virgin_Islands': 'VI',
    'Virginia': 'VA',
    'Washington': 'WA',
    'West_Virginia': 'WV',
    'Wisconsin': 'WI',
    'Wyoming': 'WY'
}

code_to_us_state = dict(map(reversed, us_state_to_code.items()))
